# Generated by Django 3.2 on 2024-11-04 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Juego')),
                ('genero', models.CharField(max_length=50, verbose_name='Género')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('pegi', models.IntegerField(choices=[(3, 'PEGI 3: Apto para todas las edades. No contiene contenido inapropiado.'), (7, 'PEGI 7: Apto para mayores de 7 años. Puede incluir miedo o violencia leve.'), (12, 'PEGI 12: Apto para mayores de 12 años. Puede contener violencia moderada o lenguaje inapropiado.'), (16, 'PEGI 16: Apto para mayores de 16 años. Puede incluir violencia más intensa, lenguaje fuerte, o contenido sexual insinuado.'), (18, 'PEGI 18: Apto solo para adultos. Puede contener violencia extrema, contenido sexual explícito, o uso de drogas.')], verbose_name='PEGI')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de Salida')),
                ('plataforma', models.CharField(max_length=50, verbose_name='Plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')])),
            ],
        ),
    ]
