# Generated by Django 3.2 on 2024-11-04 04:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El valor no puede ser negativo')], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='correo',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_distribuidora', models.CharField(max_length=100, verbose_name='Nombre de la Distribuidora')),
                ('nombre_desarrolladora', models.CharField(max_length=100, verbose_name='Nombre de la Desarrolladora')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Descuento (%)')),
                ('juegos', models.ManyToManyField(related_name='sistemas', to='aplicacion.Juego')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistemas', to='aplicacion.jugador')),
            ],
        ),
    ]
